# Initialize the node
# Copy/Paste this command in the node1 and node2 folders
# Please do not edit this file, because this file will be used for future references

geth --datadir "./data" init '<<genesis json file created>>'