# REPLACE THE <<enode>> information from the enode from bootnode process
# Copy this command to integrated terminal to launch node 1
# Node 1
# Please do not edit this file, because this file will be used for future references

geth --networkid '<<value>>' --datadir "./data" --bootnodes '<<enode>>'  --port  '<<port number>>' --ipcdisable --syncmode full console

# or for more extended command

geth --nousb --datadir "./data" --bootnodes '<<enode>>' --syncmode full --port 30310 --miner.gasprice 0 --miner.gastarget 470000000000 --http --http.addr localhost 
--http.port 8545 --http.api admin,eth,miner,net,txpool,personal,web3,clique --mine --allow-insecure-unlock --unlock "<<public address>>" --password '<<filename e.g: pwd.txt>>'
--ipcdisable console

# or
geth --nousb --datadir "./data" --bootnodes 'enode://3ee566c9067ea7b03ef1a135d5df4a8b12a3855a09f97ce0bf7dd53ba331f03fae2b5ab0e6f5bc7b17a5585719fe4f3c566d45e7b6f27bd813a86842888868d2@127.0.0.1:0?discport=30310' 
--syncmode full --port 30311 --miner.gasprice 0 --miner.gastarget 470000000000 --http --http.addr localhost --http.port 8545 --http.api admin,eth,miner,net,txpool,personal,web3,clique 
--mine --allow-insecure-unlock --unlock "0xa6673c492ee2a3002c9c4a4723b55cd0c0a05271" --password password.txt --ipcdisable console